question_data = [
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "In which city, is the Big Nickel located in Canada?",
     "correct_answer": "Sudbury, Ontario",
     "incorrect_answers": ["Calgary, Alberta", "Halifax, Nova Scotia ",
                           "Victoria, British Columbia"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "Which king was killed at the Battle of Bosworth Field in 1485? ",
     "correct_answer": "Richard III",
     "incorrect_answers": ["Edward V", "Henry VII", "James I"]},
    {"category": "Science & Nature", "type": "multiple",
     "difficulty": "medium",
     "question": "Which element has the atomic number of 7?",
     "correct_answer": "Nitrogen",
     "incorrect_answers": ["Oxygen", "Hydrogen", "Neon"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard",
     "question": "Which character from the Mega Man series made a small cameo on Volt Catfish&#039;s introduction scene in CD versions of Mega Man X3?",
     "correct_answer": "Auto",
     "incorrect_answers": ["Eddie", "Tango", "Rush"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "multiple", "difficulty": "medium",
     "question": "Ikki Kurogane is known by what nickname at the beginning of &quot;Chivalry of a Failed Knight&quot;?",
     "correct_answer": "Worst One",
     "incorrect_answers": ["Another One", "Blazer", "Princess"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "multiple", "difficulty": "medium",
     "question": "Which of these is not a world in the anime &quot;Buddyfight&quot;?",
     "correct_answer": "Ancient Dragon World",
     "incorrect_answers": ["Dragon World", "Star Dragon World",
                           "Darkness Dragon World"]},
    {"category": "Science: Computers", "type": "multiple",
     "difficulty": "hard",
     "question": "Which of these is not a layer in the OSI model for data communications?",
     "correct_answer": "Connection Layer",
     "incorrect_answers": ["Application Layer", "Transport Layer",
                           "Physical Layer"]},
    {"category": "Science & Nature", "type": "multiple",
     "difficulty": "hard",
     "question": "Which of these animals belongs in class Chondrichthyes?",
     "correct_answer": "Great white shark",
     "incorrect_answers": ["Octopus", "Killer whale", "Catfish"]},
    {"category": "Entertainment: Musicals & Theatres", "type": "multiple",
     "difficulty": "medium",
     "question": "Who played Marquis de Lafayette and Thomas Jefferson in the original Broadway run of Hamilton?",
     "correct_answer": "Daveed Diggs",
     "incorrect_answers": ["Lin-Manuel Miranda", "Javier Mu&ntilde;oz",
                           "Wayne Brady"]},
    {"category": "Entertainment: Film", "type": "boolean",
     "difficulty": "hard",
     "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
